version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/mini-css-extract-plugin"
    versions:
    - 1.2.2
    - 1.2.3
    - 1.4.0
    - 1.4.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
    - 5.0.0
    - 5.28.0
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: pixi.js
    versions:
    - 5.3.8
    - 6.0.0
    - 6.0.1
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
    - 4.0.0-beta.1
    - 4.0.0-beta.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
    - 8.1.0
    - 8.1.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: jsdom
    versions:
    - 16.5.1
    - 16.5.2
    - 16.5.3
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.15
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-modules-commonjs"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.4
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.0
    - 7.13.15
    - 7.13.5
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
    - 7.13.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 4.5.2
    - 5.3.1
  - dependency-name: jest-canvas-mock
    versions:
    - 2.3.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: "@types/optimize-css-assets-webpack-plugin"
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: "@types/copy-webpack-plugin"
    versions:
    - 6.4.0
    - 6.4.1
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: "@types/terser-webpack-plugin"
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: "@types/webpack-dev-server"
    versions:
    - 3.11.1
  - dependency-name: "@types/html-webpack-plugin"
    versions:
    - 3.2.4
    - 3.2.5
  - dependency-name: "@types/webpack-merge"
    versions:
    - 5.0.0
